services:
  web-app:
    build: .
    image: test-docker-web-app:latest
    container_name: mon-app-container
    ports:
      - "8081:5000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DD_AGENT_HOST=datadog-agent
    depends_on:
      - db
    networks:
      - devsecops-net

  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # C'est cette ligne qui sauve tes données
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - devsecops-net

networks:
  devsecops-net:
    external: true
volumes:
  postgres_data:  # <--- DÉCLARATION DU VOLUME